kumuluzee:
  name: trip-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/TripDataDS
      connection-url: jdbc:postgresql://0.0.0.0:5432/trip-data
      username: dbuser
      password: postgres
      max-pool-size: 2
  config:
    consul:
      agent: http://localhost:8500
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/TripDataDS
  metrics:
    web-instrumentation:
      - name: trip-endpoint
        url-pattern: /v1/trips
rest-properties:
  config:
    broken: false
